apiVersion: v1
kind: Service
metadata:
  name: sipstuff-operator
  namespace: sipstuff
  labels:
    app: sipstuff-operator
spec:
  type: ClusterIP
  selector:
    app: sipstuff-operator
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
